#!/bin/bash
ulimit -c unlimited

INSTDIR=`pwd`/tmp_install
export LD_LIBRARY_PATH=$INSTDIR/lib:$LD_LIBRARY_PATH
export PATH=$INSTDIR/bin:$PATH

pkill -U `whoami` -9 -e postgres
pkill -U `whoami` -9 -e pgbench

M=`pwd`/PGDATA
U=`whoami`

rm -rf $M || true
mkdir $M

rm -rf logfile.log || true

mk
export LC_ALL=C
export LANGUAGE="en_US:en"
initdb -D $M --locale=C

# autovacuum parameters. See:
# https://www.postgresql.org/docs/current/runtime-config-autovacuum.html
echo "autovacuum = 'true'" >> $M/postgresql.conf # force enable autovacuum
echo "log_autovacuum_min_duration = 0" >> $M/postgresql.conf # enable logging of all autovacuum actions
echo "autovacuum_max_workers = 10" >> $M/postgresql.conf # increase number of workers
echo "autovacuum_vacuum_threshold = 0" >> $M/postgresql.conf
echo "autovacuum_analyze_threshold = 0" >> $M/postgresql.conf
echo "autovacuum_vacuum_scale_factor = 0.0" >> $M/postgresql.conf
echo "autovacuum_naptime = 3" >> $M/postgresql.conf # minimal timeout between timeout attempts

pg_ctl -w -D $M -l logfile.log start
createdb $U

