DROP TABLE IF EXISTS p,t CASCADE;
 
CREATE TABLE p(a int) PARTITION BY HASH (a);
CREATE TABLE p1 PARTITION OF p FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE p2 PARTITION OF p FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE p3 PARTITION OF p FOR VALUES WITH (MODULUS 3, REMAINDER 2);
INSERT INTO p SELECT * FROM generate_series(1,100);

CREATE TABLE t(a int) PARTITION BY RANGE (a);
CREATE TABLE t1 PARTITION OF t FOR VALUES FROM (00) TO (10);
CREATE TABLE t2 PARTITION OF t FOR VALUES FROM (10) TO (20);
CREATE TABLE t3 PARTITION OF t FOR VALUES FROM (20) TO (30);
INSERT INTO t SELECT * FROM generate_series(0,29);

ANALYZE p,t;

explain WITH cte1 AS (
	UPDATE p SET a = a + 1 WHERE a = 10 RETURNING a
)
SELECT * FROM cte1 WHERE a>10;

explain WITH cte1 AS (
	UPDATE t SET a = a + 1 WHERE a > 10 RETURNING a
)
SELECT * FROM cte1 WHERE a<10;